CREATE SCHEMA IF NOT EXISTS audit;

CREATE TABLE IF NOT EXISTS audit.api_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(50) NOT NULL,
    method VARCHAR(10) NOT NULL,
    path VARCHAR(500) NOT NULL,
    query_string VARCHAR(2000),
    status_code INT NOT NULL,
    duration_ms BIGINT NOT NULL,
    principal_user_id UUID,
    principal_vendor_id UUID,
    principal_username VARCHAR(100),
    roles VARCHAR(500),
    ip VARCHAR(64),
    user_agent VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_api_audit_log_created_at ON audit.api_audit_log (created_at);
CREATE INDEX IF NOT EXISTS idx_api_audit_log_user_id ON audit.api_audit_log (principal_user_id);
CREATE INDEX IF NOT EXISTS idx_api_audit_log_vendor_id ON audit.api_audit_log (principal_vendor_id);

CREATE TABLE IF NOT EXISTS audit.business_replay_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direction VARCHAR(10) NOT NULL,
    service_name VARCHAR(50) NOT NULL,
    topic VARCHAR(100),
    routing_key VARCHAR(200),
    event_type VARCHAR(100) NOT NULL,
    aggregate_type VARCHAR(100),
    aggregate_id UUID,
    payload TEXT NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_business_replay_log_created_at ON audit.business_replay_log (created_at);
CREATE INDEX IF NOT EXISTS idx_business_replay_log_event_type ON audit.business_replay_log (event_type);
CREATE INDEX IF NOT EXISTS idx_business_replay_log_aggregate_id ON audit.business_replay_log (aggregate_id);

