package com.flexlease.order.domain;

public enum OrderStatus {
    PENDING_PAYMENT,
    CANCELLED,
    AWAITING_SHIPMENT,
    AWAITING_RECEIPT,
    IN_LEASE,
    RETURN_REQUESTED,
    RETURN_IN_PROGRESS,
    COMPLETED,
    BUYOUT_REQUESTED,
    BUYOUT_COMPLETED,
    EXCEPTION_CLOSED
}
