package com.flexlease.order.domain;

public enum OrderEventType {
    ORDER_CREATED,
    PAYMENT_CONFIRMED,
    ORDER_CANCELLED,
    ORDER_SHIPPED,
    ORDER_RECEIVED,
    EXTENSION_REQUESTED,
    EXTENSION_APPROVED,
    EXTENSION_REJECTED,
    RETURN_REQUESTED,
    RETURN_APPROVED,
    RETURN_REJECTED,
    BUYOUT_REQUESTED,
    BUYOUT_CONFIRMED,
    BUYOUT_REJECTED,
    COMMUNICATION_NOTE,
    PROOF_UPLOADED,
    DISPUTE_OPENED,
    DISPUTE_RESPONDED,
    DISPUTE_ESCALATED,
    DISPUTE_RESOLVED,
    SURVEY_INVITED,
    SURVEY_SUBMITTED
}
